version: '3'

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 11.15.0.0/16
         gateway: 11.15.0.1

services:
    rcp:
        build: 
            context: .
            dockerfile: rcp.dockerfile
        ports : 
            - "8545:8545"
            - "8546:8546"
        networks:
            vpcbr:
                ipv4_address: 11.15.0.92

    bootnoode:
        build: 
            context: .
            dockerfile: boot.dockerfile
        ports : 
            - "30303:30303"
        networks:
            vpcbr:
                ipv4_address: 11.15.0.93
            
    peer1:
        build: 
            context: .
            dockerfile: peer.dockerfile
        networks:
            vpcbr:
                ipv4_address: 11.15.0.94
        volumes:
            - ./data:/opt/data

    peer2:
        build: 
            context: .
            dockerfile: peer.dockerfile
        networks:
            vpcbr:
                ipv4_address: 11.15.0.95
        volumes:
            - ./data:/opt/data

    peer3:
        build: 
            context: .
            dockerfile: peer.dockerfile
        networks:
            vpcbr:
                ipv4_address: 11.15.0.96
        volumes:
            - ./data:/opt/data

    web: 
        build: 
            context: .
            dockerfile: http.dockerfile
        depends_on:
            - rcp
            - bootnoode
        ports : 
            - "80:80"
        networks:
            vpcbr:
                ipv4_address: 11.15.0.97